name: flutter_packages_cw38
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_menu_bar: ^0.1.3
  line_chart: ^1.0.5
  swipe_to: ^0.0.1+3
  pinch_zoom: ^0.0.2
  floaty_head: ^1.1.0
  url_launcher: ^5.7.0
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
